// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropCareCloud.Api.Data;

#nullable disable

namespace PropCareCloud.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706084417_AddTenantRegistrationRequests")]
    partial class AddTenantRegistrationRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.AuthUserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("auth_user_accounts", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedStaffProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RentalUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffProfileId");

                    b.HasIndex("RentalUnitId");

                    b.HasIndex("TenantProfileId");

                    b.ToTable("maintenance_requests", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.MaintenanceRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("MaintenanceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRequestId");

                    b.HasIndex("UploadedByUserProfileId");

                    b.ToTable("maintenance_request_attachments", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.MaintenanceRequestComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaintenanceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRequestId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("maintenance_request_comments", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.RentalUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Floor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("rental_units", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.TenantRegistrationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedRentalUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedUserProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RequestedPropertyOrUnit")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedRentalUnitId");

                    b.HasIndex("ApprovedUserProfileId");

                    b.HasIndex("Email");

                    b.HasIndex("ReviewedByUserProfileId");

                    b.HasIndex("Status");

                    b.HasIndex("Email", "Status");

                    b.ToTable("tenant_registration_requests", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.TenantUnitAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LeaseEndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LeaseStartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RentalUnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RentalUnitId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = TRUE AND \"LeaseEndDateUtc\" IS NULL");

                    b.HasIndex("TenantProfileId");

                    b.ToTable("tenant_unit_assignments", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.AuthUserAccount", b =>
                {
                    b.HasOne("PropCareCloud.Api.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("AuthUserAccount")
                        .HasForeignKey("PropCareCloud.Api.Domain.Entities.AuthUserAccount", "UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("PropCareCloud.Api.Domain.Entities.UserProfile", "AssignedStaffProfile")
                        .WithMany("AssignedMaintenanceRequests")
                        .HasForeignKey("AssignedStaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropCareCloud.Api.Domain.Entities.RentalUnit", "RentalUnit")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("RentalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropCareCloud.Api.Domain.Entities.UserProfile", "TenantProfile")
                        .WithMany("TenantRequests")
                        .HasForeignKey("TenantProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedStaffProfile");

                    b.Navigation("RentalUnit");

                    b.Navigation("TenantProfile");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.MaintenanceRequestAttachment", b =>
                {
                    b.HasOne("PropCareCloud.Api.Domain.Entities.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("MaintenanceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropCareCloud.Api.Domain.Entities.UserProfile", "UploadedByUserProfile")
                        .WithMany("UploadedAttachments")
                        .HasForeignKey("UploadedByUserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceRequest");

                    b.Navigation("UploadedByUserProfile");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.MaintenanceRequestComment", b =>
                {
                    b.HasOne("PropCareCloud.Api.Domain.Entities.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("Comments")
                        .HasForeignKey("MaintenanceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropCareCloud.Api.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Comments")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceRequest");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.RentalUnit", b =>
                {
                    b.HasOne("PropCareCloud.Api.Domain.Entities.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.TenantRegistrationRequest", b =>
                {
                    b.HasOne("PropCareCloud.Api.Domain.Entities.RentalUnit", "ApprovedRentalUnit")
                        .WithMany()
                        .HasForeignKey("ApprovedRentalUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropCareCloud.Api.Domain.Entities.UserProfile", "ApprovedUserProfile")
                        .WithMany()
                        .HasForeignKey("ApprovedUserProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropCareCloud.Api.Domain.Entities.UserProfile", "ReviewedByUserProfile")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedRentalUnit");

                    b.Navigation("ApprovedUserProfile");

                    b.Navigation("ReviewedByUserProfile");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.TenantUnitAssignment", b =>
                {
                    b.HasOne("PropCareCloud.Api.Domain.Entities.RentalUnit", "RentalUnit")
                        .WithMany("TenantAssignments")
                        .HasForeignKey("RentalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropCareCloud.Api.Domain.Entities.UserProfile", "TenantProfile")
                        .WithMany("TenantUnitAssignments")
                        .HasForeignKey("TenantProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RentalUnit");

                    b.Navigation("TenantProfile");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.RentalUnit", b =>
                {
                    b.Navigation("MaintenanceRequests");

                    b.Navigation("TenantAssignments");
                });

            modelBuilder.Entity("PropCareCloud.Api.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("AssignedMaintenanceRequests");

                    b.Navigation("AuthUserAccount");

                    b.Navigation("Comments");

                    b.Navigation("TenantRequests");

                    b.Navigation("TenantUnitAssignments");

                    b.Navigation("UploadedAttachments");
                });
#pragma warning restore 612, 618
        }
    }
}
